image: cimg/android:2022.08.1

stages:
  - build
  - test
  - deploy

lint-debug:
  interruptible: true
  stage: build
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assemble-debug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

unit-test:
  interruptible: true
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
